name: Upload Django Static Files to S3

on:
  push:
    branches:
      - main

jobs:
  upload-static:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Check AWS caller identity
        run: aws sts get-caller-identity
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_S3_REGION_NAME }}

      # # Sync static files to S3 using STATICFILES_STORAGE = 'django_static.storage_backends.StaticStorage' variable
      # - name: Run collectstatic (by using S3Boto3Storage module)
      #   env:
      #     AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      #     AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      #     AWS_STORAGE_BUCKET_NAME: ${{ secrets.AWS_STORAGE_BUCKET_NAME }}
      #     AWS_S3_REGION_NAME: ${{ secrets.AWS_S3_REGION_NAME }}
      #     CLOUDFRONT_DOMAIN: ${{ secrets.CLOUDFRONT_DOMAIN }}
      #     DJANGO_SETTINGS_MODULE: django_static.settings
      #   run: |
      #     python manage.py collectstatic --noinput


      # Sync static files to S3 using aws s3 sync command
      - name: Collect static files
        run: python manage.py collectstatic --noinput

      - name: Sync static files to S3
        run: |
          aws s3 sync ./static/ s3://your-bucket-name/static/ --delete
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_S3_REGION_NAME }}